#!/usr/bin/env node
// Codegen for @eutectic/contracts (M0-SH-03).
//
//   openapi.yaml  ──openapi-typescript──▶  generated/schema.ts
//                 ──this script────────▶  generated/client.ts
//                 ──this script────────▶  generated/server-types.ts
//
// Deterministic by construction: output order follows the spec file, nothing
// reads the clock or the environment. Running it twice produces no diff, so CI
// can diff `generated/` for staleness.

import { execFileSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const specPath = path.join(packageRoot, 'openapi.yaml');
const outDir = path.join(packageRoot, 'generated');

const BANNER = [
  '// Generated by `pnpm --filter @eutectic/contracts generate`. Do not edit.',
  '// Source of truth: packages/contracts/openapi.yaml',
  '',
].join('\n');

const HTTP_METHODS = new Set(['get', 'put', 'post', 'delete', 'patch', 'options', 'head', 'trace']);
const MUTATING = new Set(['put', 'post', 'delete', 'patch']);

export const SPEC_PATH = specPath;
export const OUT_DIR = outDir;

/** Scans the spec for (path, method, operationId). The spec's indentation is
 *  fixed and validated below, so this needs no YAML parser — and this package
 *  takes no runtime dependency to read its own source of truth. */
export function scanOperations(yaml) {
  const lines = yaml.split('\n');
  const operations = [];
  let inPaths = false;
  let currentPath = null;
  let pending = null;

  const flush = () => {
    if (pending) {
      throw new Error(`operation ${pending.method.toUpperCase()} ${pending.path} has no operationId`);
    }
  };

  for (const line of lines) {
    if (/^paths:\s*$/.test(line)) {
      inPaths = true;
      continue;
    }
    if (!inPaths) continue;
    if (/^\S/.test(line)) {
      flush();
      inPaths = false;
      continue;
    }

    const pathMatch = /^ {2}(\/\S*):\s*$/.exec(line);
    if (pathMatch) {
      flush();
      currentPath = pathMatch[1];
      continue;
    }

    const methodMatch = /^ {4}([a-z]+):\s*$/.exec(line);
    if (methodMatch && HTTP_METHODS.has(methodMatch[1])) {
      flush();
      if (!currentPath) throw new Error(`method ${methodMatch[1]} outside a path`);
      pending = { path: currentPath, method: methodMatch[1] };
      continue;
    }

    const idMatch = /^ {6}operationId: (\w+)\s*$/.exec(line);
    if (idMatch) {
      if (!pending) throw new Error(`operationId ${idMatch[1]} outside an operation`);
      operations.push({ ...pending, operationId: idMatch[1], successStatus: null });
      pending = null;
      continue;
    }

    // Response codes are quoted keys at exactly 8-space indent, after the
    // operationId. The lowest 2xx/3xx is the operation's success status.
    const statusMatch = /^ {8}'(\d{3})':/.exec(line);
    if (statusMatch && operations.length > 0) {
      const status = Number(statusMatch[1]);
      const op = operations[operations.length - 1];
      if (status >= 200 && status < 400 && (op.successStatus === null || status < op.successStatus)) {
        op.successStatus = status;
      }
    }
  }
  flush();

  if (operations.length === 0) throw new Error('no operations found in openapi.yaml');
  const seen = new Set();
  for (const op of operations) {
    if (seen.has(op.operationId)) throw new Error(`duplicate operationId: ${op.operationId}`);
    seen.add(op.operationId);
    if (op.successStatus === null) {
      throw new Error(`operation ${op.operationId} declares no 2xx/3xx response`);
    }
  }
  return operations;
}

function typeName(operationId) {
  return operationId.charAt(0).toUpperCase() + operationId.slice(1);
}

function runOpenapiTypescript() {
  const pkgJsonPath = require.resolve('openapi-typescript/package.json');
  const pkgJson = JSON.parse(readFileSync(pkgJsonPath, 'utf8'));
  const bin = typeof pkgJson.bin === 'string' ? pkgJson.bin : pkgJson.bin['openapi-typescript'];
  const binPath = path.join(path.dirname(pkgJsonPath), bin);
  execFileSync(process.execPath, [binPath, specPath, '--output', path.join(outDir, 'schema.ts')], {
    stdio: ['ignore', 'ignore', 'inherit'],
    cwd: packageRoot,
  });
}

export function renderClient(operations) {
  const lines = [
    BANNER,
    "import { createRequester, type ClientOptions, type GenericArgs } from '../src/runtime.js';",
    "import type { ClientArgs, OperationArgs, OperationResult } from '../src/op-types.js';",
    "import type { operations } from './schema.js';",
    '',
  ];

  for (const op of operations) {
    const name = typeName(op.operationId);
    lines.push(`export type ${name}Args = OperationArgs<operations['${op.operationId}']>;`);
    lines.push(`export type ${name}Result = OperationResult<operations['${op.operationId}']>;`);
  }
  lines.push('');

  lines.push('/** The typed surface of the Eutectic API. One method per operationId. */');
  lines.push('export interface EutecticClient {');
  for (const op of operations) {
    const name = typeName(op.operationId);
    lines.push(`  /** \`${op.method.toUpperCase()} ${op.path}\` */`);
    lines.push(
      `  ${op.operationId}(...args: ClientArgs<operations['${op.operationId}']>): Promise<${name}Result>;`,
    );
  }
  lines.push('}');
  lines.push('');

  lines.push('export function createClient(options: ClientOptions): EutecticClient {');
  lines.push('  const call = createRequester(options);');
  lines.push('  return {');
  for (const op of operations) {
    const name = typeName(op.operationId);
    lines.push(
      `    ${op.operationId}: (...args) =>`,
      `      call('${op.method}', '${op.path}', args[0] as GenericArgs | undefined) as Promise<${name}Result>,`,
    );
  }
  lines.push('  };');
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

export function renderServerTypes(operations) {
  const lines = [
    BANNER,
    "import type { HttpMethod } from '../src/runtime.js';",
    "import type { OperationRequest, OperationResult, RouteHandler } from '../src/op-types.js';",
    "import type { components, operations, paths } from './schema.js';",
    '',
    'export type Schemas = components[\'schemas\'];',
    'export type ApiPaths = paths;',
    'export type ApiOperations = operations;',
    'export type OperationId = keyof operations;',
    '',
  ];

  for (const op of operations) {
    const name = typeName(op.operationId);
    lines.push(`export type ${name}Request = OperationRequest<operations['${op.operationId}']>;`);
    lines.push(`export type ${name}Reply = OperationResult<operations['${op.operationId}']>;`);
    lines.push(`export type ${name}Handler = RouteHandler<operations['${op.operationId}']>;`);
  }
  lines.push('');

  lines.push('export interface RouteDescriptor {');
  lines.push('  readonly method: HttpMethod;');
  lines.push('  readonly path: string;');
  lines.push('  readonly mutating: boolean;');
  lines.push('  readonly successStatus: number;');
  lines.push('}');
  lines.push('');
  lines.push('/** Every operation in the contract. `apps/api` asserts its registered routes');
  lines.push(' *  match this table exactly — that is the route-parity gate (system-design §2). */');
  lines.push('export const ROUTES = {');
  for (const op of operations) {
    lines.push(
      `  ${op.operationId}: { method: '${op.method}', path: '${op.path}', mutating: ${MUTATING.has(op.method)}, successStatus: ${op.successStatus} },`,
    );
  }
  lines.push('} as const satisfies Record<OperationId, RouteDescriptor>;');
  lines.push('');
  lines.push('export type RouteTable = typeof ROUTES;');
  lines.push('');

  return lines.join('\n');
}

function main() {
  const yaml = readFileSync(specPath, 'utf8');
  const operations = scanOperations(yaml);
  mkdirSync(outDir, { recursive: true });
  runOpenapiTypescript();
  writeFileSync(path.join(outDir, 'client.ts'), renderClient(operations), 'utf8');
  writeFileSync(path.join(outDir, 'server-types.ts'), renderServerTypes(operations), 'utf8');
  process.stdout.write(`contracts: generated 3 files from ${operations.length} operations\n`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main();
}
